name: Deploy Avro Frontend
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_kb:
        description: 'Deploy KB as well?'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-fe:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci --prefer-offline
      - name: Cache Quartz build
        uses: actions/cache@v4
        with:
          path: |
            public/static
            .quartz-cache
          key: quartz-build-${{ runner.os }}-${{ hashFiles('content/**', 'quartz/**') }}
          restore-keys: |
            quartz-build-${{ runner.os }}-
      - name: Build Quartz Frontend
        run: npx quartz build --concurrency=4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload Frontend artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: frontend-pages
          path: public
          retention-days: 1

  deploy-fe:
    needs: build-fe
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: frontend-pages

  build-kb:
    runs-on: ubuntu-22.04
    if: github.event_name == 'workflow_dispatch' && inputs.deploy_kb == true
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: kb/package-lock.json
      - name: Install KB Dependencies
        working-directory: ./kb
        run: npm ci --prefer-offline
      - name: Cache KB Quartz build
        uses: actions/cache@v4
        with:
          path: |
            kb/public/static
            kb/quartz/build
          key: kb-quartz-build-${{ runner.os }}-${{ hashFiles('kb/content/**', 'kb/quartz/**') }}
          restore-keys: |
            kb-quartz-build-${{ runner.os }}-
      - name: Build KB Quartz
        working-directory: ./kb
        run: npx quartz build --concurrency=4
      - name: Upload KB artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: kb-pages
          path: kb/public
          retention-days: 1

  deploy-kb:
    needs: build-kb
    if: always() && needs.build-kb.result == 'success'
    environment:
      name: kb-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout KB submodule
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download KB artifact
        uses: actions/download-artifact@v4
        with:
          name: kb-pages
          path: ./kb-build
      - name: Deploy KB to its repository
        working-directory: ./kb
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Copy built files to kb repo
          rm -rf public/*
          cp -r ../kb-build/* public/
          
          # Commit and push to kb repository
          git add public/
          git commit -m "Deploy KB from avro-fe workflow [skip ci]" || exit 0
          git push origin main
